version: '3'

services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome-node:
    image: selenium/node-chrome
    shm_size: "2g"
    container_name: chrome-node
    ports:
      - "4443:4444"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox-node:
    image: selenium/node-firefox
    shm_size: "2g"
    container_name: firefox-node
    ports:
      - "4442:4444"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  testng-project:
    build: .
    depends_on:
      - selenium-hub
    volumes:
      - ./src:/usr/src/app/src
      - /Users/codeclouds-bikram/Desktop/AutomationMac/pom.xml:/usr/src/app/pom.xml  # Change this line
    environment:
      - HUB_HOST=http://selenium-hub:4444/wd/hub
    container_name: testng-project
